#!/usr/bin/env ksh
# by Roberto Rodriguez Jr <brainacid9@gmail.com>

. ./pnk.lang

wt=cmdText
ws=cmdCli
ap=app

ZDshebang
ZDfrm tkinter Tk,Text,Label,Entry,Frame,PanedWindow,PhotoImage
ZDfrm subprocess run
ZDfrm re finditer
ZDimp datetime

Zztoorwin App
XIfv - catImg PhotoImage 'file="cat.png"'
XFfc z wm_iconphoto False,catImg

Xzpnwin pw '"horizontal"'
XFbinda Control-r runit 

XFfc z runit


YDdefe runit
XIcv $ap Textapp 
XFpk $ap 1 both
XFfc zz pw.add $ap


ZDcld Textapp

Xzpnwin pww '"vertical"'

Xztext $ws 0 x
XFpk $ws 1 both
XFcfg $ws. height=8
XFfc z pww.add self.$ws

XFbind $ws Escape clearCmd
XFbind $ws Control-l clearTxt
XFbind $ws Control-J changeCmdbg
XFbind $ws Control-G changeCmdfg
XFbind $ws Control-W changeCmdfnt
XFbind $ws Control-j changeTxtbg
XFbind $ws Control-g changeTxtfg
XFbind $ws Control-w changeTxtfnts
XFbind $ws Control-s savefile
XFbind $ws Alt-o openfile
XFbind $ws Control-Shift_R mapdShell
XFbind $ws Shift-Shift_R innerShell
XFbind $ws Control-Return sendCode
XFbind $ws Alt-Return sendline
XFbind $ws Control-Shift-Return sendAll
XFbind $ws Shift_R padSyntax

Xztext $wt
XFpk $wt 1 both	
XFfc z pww.add self.$wt

XFbind $wt Shift-Shift_R normalShell
XFbind $wt Shift_R padSyntax

XFfc z $ws.focus
XFfc z padTagConf
XFfc z digitTagconf
XFopft $ws '"hist.pnk"'




YDdefe padTagConf
XIv - d '{ "arg": ("#333", "#eccca2"), "args": ("#444", "#eccca2"), "Z": ("green", "green"), "Y": ("#bfff00", "#bfff00"), "X": ("#ffb732", "#ffb732"), "W": ("#00ffff", "#00ffff"), "V": ("blue", "blue"), "U": ("#430075", "#430075"), "L": ("red", "red"), "K": ("blue", "blue"), "F": ("green", "green"), "I": ("#ffff32", "#ffff32"), "D": ("purple", "purple"),  "z": ("pink", "pink"), }'
XLffor key,value d.items
WFtagcfg $wt key value[0] value[1]
WFtagcfg $ws key value[0] value[1]


YDdefe digitTagconf
XIv - d '{"0": ("#ffff00", "#ffff00"), "1": ("#ffa500", "#ffa500"), "2": ("#ff00ff", "#ff00ff"), "3": ("#ff0000", "#ff0000"), "4": ("pink", "pink"), "5": ("lime", "lime"), "6": ("#0000ff", "#0000ff"), "7": ("green", "green"), "8": ("gray", "gray"), "9": ("white", "white"),}'
XLffor key,value d.items
WFtagcfg $wt key value[0] value[1]
WFtagcfg $ws key value[0] value[1]


YDdefp chgfnt gg
XIv z gg gg
XFcfg $ws. 'font=("Iosevka",gg)'


YDdefe openfile
XFfc z chgfnt 48
XItgetln $ws filename
XFopft $wt filename
XFtins $ws 1.0 "f\"$datenow {filename} Opened!\n\""
XFfc z ersAct
XFfc z padSyntax


YDdefe savefile
XFfc z padSyntax
XFfc z savesrc
XFfc z chgfnt 48
XItgetln $ws filename
XItgeta $wt data 
XFwrtf data filename
XFtins $ws 1.0 "f\"$datenow {filename} Saved!\n\""
XFfc z ersAct


YDdefe ersMsg
XFtdel $ws 1.0 1.end+1c
XFfc z chgfnt 12


YDdefe ersAct
XFfc z after 3000,self.ersMsg


YDdefe savesrc
XIv - filename '"hist.pnk"'
XItgeta $ws data 
XFwrtf data filename
XFfc z padSyntax


YDdefe changeCmdfnt
XItgetln $ws fnts
XIv - fn 'int(fnts)'
XFcfg $ws. 'font=("Iosevka",fn)'


YDdefe changeCmdfg
XItgetln $ws fgcolor
XFcfg $ws. 'fg=fgcolor'


YDdefe changeCmdbg
XItgetln $ws bgcolor
XFcfg $ws. 'bg=bgcolor'


YDdefe changeTxtfnts
XItgetln $ws fnts
XIv - fn 'int(fnts)'
XFcfg $wt. 'font=("Iosevka",fn)'


YDdefe changeTxtfg
XItgetln $ws fgcolor
XFcfg $wt. 'fg=fgcolor'


YDdefe changeTxtbg
XItgetln $ws bgcolor
XFcfg $wt. 'bg=bgcolor'


YDdefe clearCmd
XFtdel $ws 1.0 end


YDdefe clearTxt
XFtdel $wt 1.0 end


YDdefp mapdef com
XFshsp2 $wt 'f". ./pnk.lang; {com}"'


YDdefe mapdShell
XItgetln $ws cmd
XFfc z mapdef cmd
XFfc z $wt.see '"1.0"'


YDdefe innerShell
XItgetln $ws linecom
XFtins $ws 'insert lineend' '" #|;"'
XFshsp $ws linecom
XFfc z $ws.see '"end"'


YDdefe normalShell
XItgetln $wt linecom
XFtins $wt 'insert lineend' '" #|;"'
XFshsp $wt linecom
XFfc z $wt.see '"end"'


YDdefe sendAll
XItgeta $ws txt
XFtins $wt end 'f"{txt}\n"'
XFfc z $wt.see '"end"'
XFfc z padSyntax


YDdefe sendline
XItgetln $ws txt
XFtins $wt end 'f"{txt}\n"'
XFfc z $wt.see '"end"'
XFfc z padSyntax


YDdefe sendCode
XItgetln $ws txt
XIfv - tt txt.split

Xzmap Xzmap x00 3

Xzmap '. ./pnk.lang' a00 0
Xzmap ZDsheimpang a01 0
Xzmap ZDfrm a02 2
Xzmap ZDimp a10 1
Xzmap ZDas a11 2
Xzmap Zztoorwin a12 1

Xzmap XIcv b00 2
Xzmap ZDcld b01 3 #pnk
Xzmap ZDcld b02 1 #py
Xzmap ZDdc b10 2
Xzmap ZFmain b11 2

Xzmap ZDfd c00 3
Xzmap YDfd c01 3
Xzmap XDfd c02 3
Xzmap WDfd c10 3

Xzmap ZDdefe d00 1
Xzmap YDret  d01 1
Xzmap YDdefs d10 2
Xzmap YDdefp d12 2
Xzmap YDdefe d20 1
Xzmap XDret d11 1
Xzmap XDdefe d20 1
Xzmap XDdefs d22 2
Xzmap WDret d21 1
Xzmap WDdefe d30 1
Xzmap WDdefs d32 2
Xzmap VDret d31 1

Xzmap ZFfc e00 3
Xzmap YFfc e01 3
Xzmap XFfc e02 3
Xzmap WFfc e10 3
Xzmap VFfc e11 3
Xzmap UFfc e12 3

Xzmap ZIfv f00 4
Xzmap YIfv f01 4
Xzmap XIfv f02 4
Xzmap WIfv f10 4
Xzmap VIfv f11 4
Xzmap UIfv f12 4

Xzmap ZIv g00 3
Xzmap YIv g01 3
Xzmap XIv g02 3
Xzmap WIv g10 3
Xzmap VIv g11 3
Xzmap UIv g12 3

Xzmap ZIac h00 3
Xzmap YIac h01 3
Xzmap XIac h02 3
Xzmap WIac h10 3
Xzmap VIac h11 3
Xzmap UIac h12 3

Xzmap YKtry i00 0
Xzmap YKexcp i01 1
Xzmap YKfin i02 0
Xzmap XKtry i10 0
Xzmap XKexcp i11 1
Xzmap XKfin i12 0
Xzmap WKtry i20 0
Xzmap WKexcp i21 1
Xzmap WKfin i22 0
Xzmap VKtry i30 0
Xzmap VKexcp i31 1
Xzmap VKfin i32 0

Xzmap ZKif j00 1
Xzmap YKif j01 1
Xzmap XKif j02 1
Xzmap WKif j10 1
Xzmap VKif j11 1
Xzmap ZKelif k00 1
Xzmap YKelif k01 1
Xzmap XKelif k02 1
Xzmap WKelif k10 1
Xzmap VKelif k11 1
Xzmap ZKelse l00 1
Xzmap YKelse l01 1
Xzmap XKelse l02 1
Xzmap WKelse l10 1
Xzmap VKelse l11 1

Xzmap ZLfor m00 2
Xzmap YLfor m01 2
Xzmap XLfor m02 2
Xzmap WLfor m10 2
Xzmap VLfor m11 2
Xzmap ULfor m12 2
Xzmap ZLffor m20 2
Xzmap YLffor m21 2
Xzmap XLffor m22 2
Xzmap WLffor m30 2
Xzmap VLffor m31 2
Xzmap ULffor m32 2
Xzmap ZLwhile m40 1
Xzmap YLwhile m41 1
Xzmap XLwhile m42 1
Xzmap WLwhile m50 1
Xzmap VLwhile m51 1
Xzmap ULwhile m52 1

Xzmap Xzbtn w00 3
Xzmap Xztext w01 1
Xzmap Xzpnwin w02 2
Xzmap Xznotebk w10 3
Xzmap Xzentry w11 1
Xzmap Xzlabel w12 3

Xzmap XFpk p00 4
Xzmap XFpl p01 3
Xzmap XFbind p02 2
Xzmap XFbinda p10 2

Xzmap XIeget t00 2
Xzmap XItgetln t01 2
Xzmap XItget t02 4
Xzmap XItgeta t10 2

Xzmap XFshsp s00 2
Xzmap XFshsp2 s01 2

Xzmap XFopft v02 2
Xzmap XFwrtf v10 2
Xzmap XFset v11 2
Xzmap XFcfg v12 2
Xzmap XFedel v20 1
Xzmap XFeins v21 2
Xzmap XFtdel v22 3
Xzmap XFtlndel v30 1
Xzmap XFtins v31 3

Xzmap WFtagcfg u00 4
Xzmap WFtins u01 3

#Xzmap VFtins
#Xzmap WFset
#Xzmap WFcfg
#Xzmap WFedel
#Xzmap WFeins
#Xzmap WFtdel
#Xzmap WFtlndel
#Xzmap WFtins
#Xzmap WFtgetln
#Xzmap WFtgtln
XFfc z padSyntax
XFfc z cliSyntax
XFfc z $wt.see '"end"'


YDdefe padSyntax
XFfc zz syntax $wt


YDdefe cliSyntax
XFfc zz syntax $ws


YDdefp syntax xx
XIv z xx xx
XItgeta xx data

XIv - SQ_idx "[(m.start(),m.end()) for m in finditer(r'\'(.*?)\'', data)]"
XLfor start,end SQ_idx
WFfc z xx.tag_add '"arg",f"1.0+{start}c",f"1.0+{end}c"'

XIv - DQ_idx "[(m.start(),m.end()) for m in finditer(r'\"(.*?)\"', data)]"
XLfor start,end DQ_idx
WFfc z xx.tag_add '"args",f"1.0+{start}c",f"1.0+{end}c"'

XIv - Z_idx "[(m.start(),m.end()) for m in finditer(r'Z', data)]"
XLfor start,end Z_idx
WFfc z xx.tag_add '"Z",f"1.0+{start}c",f"1.0+{end}c"'

XIv - z_idx "[(m.start(),m.end()) for m in finditer(r'z', data)]"
XLfor start,end z_idx
WFfc z xx.tag_add '"z",f"1.0+{start}c",f"1.0+{end}c"'

XIv - D_idx "[(m.start(),m.end()) for m in finditer(r'D', data)]"
XLfor start,end D_idx
WFfc z xx.tag_add '"D",f"1.0+{start}c",f"1.0+{end}c"'

XIv - F_idx "[(m.start(),m.end()) for m in finditer(r'F', data)]"
XLfor start,end F_idx
WFfc z xx.tag_add '"F",f"1.0+{start}c",f"1.0+{end}c"'

XIv - I_idx "[(m.start(),m.end()) for m in finditer(r'I', data)]"
XLfor start,end I_idx
WFfc z xx.tag_add '"I",f"1.0+{start}c",f"1.0+{end}c"'

XIv - K_idx "[(m.start(),m.end()) for m in finditer(r'K', data)]"
XLfor start,end K_idx
WFfc z xx.tag_add '"K",f"1.0+{start}c",f"1.0+{end}c"'

XIv - L_idx "[(m.start(),m.end()) for m in finditer(r'L', data)]"
XLfor start,end L_idx
WFfc z xx.tag_add '"L",f"1.0+{start}c",f"1.0+{end}c"'

XIv - U_idx "[(m.start(),m.end()) for m in finditer(r'U', data)]"
XLfor start,end U_idx
WFfc z xx.tag_add '"U",f"1.0+{start}c",f"1.0+{end}c"'

XIv - V_idx "[(m.start(),m.end()) for m in finditer(r'V', data)]"
XLfor start,end V_idx
WFfc z xx.tag_add '"V",f"1.0+{start}c",f"1.0+{end}c"'

XIv - W_idx "[(m.start(),m.end()) for m in finditer(r'W', data)]"
XLfor start,end W_idx
WFfc z xx.tag_add '"W",f"1.0+{start}c",f"1.0+{end}c"'

XIv - X_idx "[(m.start(),m.end()) for m in finditer(r'X', data)]"
XLfor start,end X_idx
WFfc z xx.tag_add '"X",f"1.0+{start}c",f"1.0+{end}c"'

XIv - Y_idx "[(m.start(),m.end()) for m in finditer(r'Y', data)]"
XLfor start,end Y_idx
WFfc z xx.tag_add '"Y",f"1.0+{start}c",f"1.0+{end}c"'


XIv - l0_idx "[(m.start(),m.end()) for m in finditer(r'0', data)]"
XLfor start,end l0_idx
WFfc z xx.tag_add '"0",f"1.0+{start}c",f"1.0+{end}c"'

XIv - l1_idx "[(m.start(),m.end()) for m in finditer(r'1', data)]"
XLfor start,end l1_idx
WFfc z xx.tag_add '"1",f"1.0+{start}c",f"1.0+{end}c"'

XIv - l2_idx "[(m.start(),m.end()) for m in finditer(r'2', data)]"
XLfor start,end l2_idx
WFfc z xx.tag_add '"2",f"1.0+{start}c",f"1.0+{end}c"'

XIv - l3_idx "[(m.start(),m.end()) for m in finditer(r'3', data)]"
XLfor start,end l3_idx
WFfc z xx.tag_add '"3",f"1.0+{start}c",f"1.0+{end}c"'

XIv - l4_idx "[(m.start(),m.end()) for m in finditer(r'4', data)]"
XLfor start,end l4_idx
WFfc z xx.tag_add '"4",f"1.0+{start}c",f"1.0+{end}c"'

XIv - l5_idx "[(m.start(),m.end()) for m in finditer(r'5', data)]"
XLfor start,end l5_idx
WFfc z xx.tag_add '"5",f"1.0+{start}c",f"1.0+{end}c"'

XIv - l6_idx "[(m.start(),m.end()) for m in finditer(r'6', data)]"
XLfor start,end l6_idx
WFfc z xx.tag_add '"6",f"1.0+{start}c",f"1.0+{end}c"'

XIv - l7_idx "[(m.start(),m.end()) for m in finditer(r'7', data)]"
XLfor start,end l7_idx
WFfc z xx.tag_add '"7",f"1.0+{start}c",f"1.0+{end}c"'

XIv - l8_idx "[(m.start(),m.end()) for m in finditer(r'8', data)]"
XLfor start,end l8_idx
WFfc z xx.tag_add '"8",f"1.0+{start}c",f"1.0+{end}c"'

XIv - l9_idx "[(m.start(),m.end()) for m in finditer(r'9', data)]"
XLfor start,end l9_idx
WFfc z xx.tag_add '"9",f"1.0+{start}c",f"1.0+{end}c"'

ZFmain App 'pnk-ide'
